### ISSUE TITLE
Add a "Ready to Play" button to the client.

### ISSUE THREAD

**Issue by KebertXela87** [KebertXela87/CluelessGUI#15]
This will tell the gamecontroller you are ready.
Once each connected player is "ready", the gamecontroller will kick off the game start method.

Add server-side logic as well.

catch tag = "readytoplay"

**Comment by Hangulandy** [comment]
Server-side logic implemented (catch added in ClientHandler, setIsReady() is called from the case statement for reading; this then sets the player ready status, broadcasts the status to the other players, and attempts to start the game by calling the game controller)

**Comment by KebertXela87** [comment]
created the Ready to Play button and tested functionality.
